use_frameworks!

target 'UIViewChainable_Example' do
  pod 'UIViewChainable', :path => '../'

  target 'UIViewChainable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
